In [1]:
import datajoint as dj
from microns_phase3 import nda, utils
import pandas as pd
import numpy as np

Connecting microns@db.datajoint.com:3306


In [48]:
unit_key = {'session': 4, 'scan_idx': 7, 'unit_id':1262}
#Select the movie trials in the appropiate session and scan
trial_key = {'session': 4, 'scan_idx': 7}
trial_info = nda.Trial & trial_key

/usr/local/lib/python3.9/site-packages/datajoint/connection.py:219: UserWarning: MySQL server has gone away. Reconnecting to the server.
  warnings.warn("MySQL server has gone away. Reconnecting to the server.")


In [42]:
nda.ScanTimes & trial_key

KeyboardInterrupt: 

In [49]:
trial_info* nda.Monet2

*session    *scan_idx    *trial_idx    *condition_has type           start_idx     end_idx     start_frame_ti end_frame_time stim_times fps        duration     rng_seed     blue_green_sat pattern_width  pattern_aspect temp_kernel    temp_bandwidth ori_coherence  ori_fraction   ori_mix     n_dirs     speed     directions onsets     movie     
+---------+ +----------+ +-----------+ +------------+ +------------+ +-----------+ +---------+ +------------+ +------------+ +--------+ +--------+ +----------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------------+ +---------+ +--------+ +-------+ +--------+ +--------+ +--------+
4           7            6             DKYV7TrfEl+C8n stimulus.Monet 435           529         69.11870193481 84.10179495811 =BLOB=     60.000     15.000       4407.0       0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            7             +rgSVBVRE8Ij1W stimulus.Monet 530           624         84.18511772155 99.16820192337 =BLOB=     60.000     15.000       2.0          0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            8             GHn0W57E+2PS+Q stimulus.Monet 625           719         99.25153255462 114.2346186637 =BLOB=     60.000     15.000       8.0          0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            9             u0ftbdrw9UHzSH stimulus.Monet 720           814         114.3179526329 129.3010439872 =BLOB=     60.000     15.000       1193.0       0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            88            WdUz9wrTqcT0KJ stimulus.Monet 6138          6232        974.5038266181 989.4869055747 =BLOB=     60.000     15.000       3935.0       0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            89            CJhwNJFKI+lyFV stimulus.Monet 6233          6327        989.5535707473 1004.536656618 =BLOB=     60.000     15.000       4566.0       0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            90            SzeVJsDzE+Ceeb stimulus.Monet 6328          6422        1004.619989633 1019.603076696 =BLOB=     60.000     15.000       5.0          0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            91            WD0uyxvusJmVxf stimulus.Monet 6423          6517        1019.686408758 1034.669495582 =BLOB=     60.000     15.000       1.0          0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            98            YLuStB2eXkgOS+ stimulus.Monet 6898          6992        1095.168509006 1110.151603698 =BLOB=     60.000     15.000       9.0          0.000          72             1.7            hamming        4.00           2.50           1.0            1.0         16         0.2       =BLOB=     =BLOB=     =BLOB=    
4           7            99            gnsVaYRshZj1q1 stimulus.Monet 6993          7087        1110.234927654 1125.218015670 =BLOB=     60.000     15.000       8213.0       0.000          72             1.7          

In [50]:
dirs = (trial_info* nda.Monet2).fetch('directions')


In [51]:
dirs[0]

array([[ 90. , 315. , 157.5,  22.5, 180. , 135. , 292.5, 270. , 247.5,
        202.5, 337.5,   0. ,  45. ,  67.5, 225. , 112.5]])

In [35]:
nda.Activity() & unit_key

*session    *scan_idx    *unit_id    trace     
+---------+ +----------+ +---------+ +--------+
8           7            1           =BLOB=    
8           7            2           =BLOB=    
8           7            3           =BLOB=    
8           7            4           =BLOB=    
8           7            5           =BLOB=    
8           7            6           =BLOB=    
8           7            7           =BLOB=    
8           7            8           =BLOB=    
8           7            9           =BLOB=    
8           7            10          =BLOB=    
8           7            11          =BLOB=    
8           7            12          =BLOB=    
   ...
 (Total: 7927)

In [52]:
spike_trace = (nda.Activity() & unit_key).fetch1('trace')

In [54]:
spike_trace.shape

(40000,)

In [46]:
#Extract start and end frames these have the same shape as the dirs matrix, ntrials
#each item is the start or end id
s = (trial_info * nda.Monet2).fetch('start_idx')
e = (trial_info * nda.Monet2).fetch('end_idx')

In [14]:
s, e

(array([  435,   530,   625,   720,  6138,  6233,  6328,  6423,  6898,
         6993,  7088,  7183,  9939, 10034, 10129, 10223, 14122, 14217,
        14312, 14407, 16784, 16878, 16973, 17068, 17163, 17258, 17353,
        17448, 18684, 18779, 18874, 18968, 22487, 22582, 22676, 22771,
        22866, 22961, 23056, 23151]),
 array([  529,   624,   719,   814,  6232,  6327,  6422,  6517,  6992,
         7087,  7182,  7277, 10033, 10128, 10222, 10317, 14216, 14311,
        14406, 14501, 16877, 16972, 17067, 17162, 17257, 17352, 17447,
        17542, 18778, 18873, 18967, 19062, 22581, 22675, 22770, 22865,
        22960, 23055, 23150, 23244]))

In [16]:
onsets = (trial_info * nda.Monet2).fetch('onsets')

In [22]:
np.diff(onsets[0])

array([[0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375,
        0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375, 0.9375]])

In [23]:
onsets[0]

array([[ 0.    ,  0.9375,  1.875 ,  2.8125,  3.75  ,  4.6875,  5.625 ,
         6.5625,  7.5   ,  8.4375,  9.375 , 10.3125, 11.25  , 12.1875,
        13.125 , 14.0625]])